Name: <green><b>旅行者商店</b></green>
Description:
- <gray>商品每24小时更换的商店。</gray>
- <gray>每24小时更换。</gray>
Permission_Required: false
Layout:
  Name: default
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: true
Rotation:
  Type: INTERVAL
  Interval: 86400
  Products:
    Min_Amount: 15
    Max_Amount: 15
    Slots: 10,11,12,13,14,15,16,20,21,22,23,24,30,31,32
Icon:
  Material: ENDER_EYE