List:
  experience_bottle:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb400dmqqbeclhn4ob6egt6au3gclp6ipbecdiluojfehq6op80
      Item: 180000o00lhmutbeeg00000110004qb400dmqqbeclhn4ob6egt6au3gclp6ipbecdiluojfehq6op80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  ender_eye:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qcln68pbibtinip80
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qcln68pbibtinip80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 15.0
      BUY: 350.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  iron_ingot:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej9e9nmsnr9dpjmut00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej9e9nmsnr9dpjmut00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  gold_ingot:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej7dtm68nr9dpjmut00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej7dtm68nr9dpjmut00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  lapis_lazuli:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6oobgd5plur31f9qmoq80
      Item: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6oobgd5plur31f9qmoq80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  flint:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ej6dhkmst00
      Item: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ej6dhkmst00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  egg:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79imepo0
      Item: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79imepo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 5.0
      BUY: 25.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  tnt:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79q6st00
      Item: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79q6st00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 35.0
      BUY: 400.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  carrot:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3kor1e9p6ut00
      Item: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3kor1e9p6ut00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 5.0
      BUY: 35.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  gold_nugget:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kprfdhi5urjlctjmat00
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kprfdhi5urjlctjmat00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  iron_nugget:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kqbidtn5urjlctjmat00
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kqbidtn5urjlctjmat00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  wheat:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ejnd1im2t00
      Item: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ejnd1im2t00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  stick:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ejjehkm6qo0
      Item: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ejjehkm6qo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  leather:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb4008mqqbeclhn4ob6egt6opb1ehk6asg0
      Item: 180000o00lhmutbeeg00000110004qb4008mqqbeclhn4ob6egt6opb1ehk6asg0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  copper_ingot:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt66rrge1in4nr9dpjmut00
      Item: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt66rrge1in4nr9dpjmut00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  gray_dye:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79jn4obpbti7ip80
      Item: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79jn4obpbti7ip80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 1.0
      BUY: 15.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  book:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qc9nmuqo0
      Item: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qc9nmuqo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 1.0
      BUY: 10.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  glass_bottle:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6er31edpluojfehq6op80
      Item: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6er31edpluojfehq6op80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 2.0
      BUY: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  melon_slice:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3krb5dhnmsnrjdhkm6p80
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3krb5dhnmsnrjdhkm6p80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  nautilus_shell:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800odlkmspb3e9gmct1qdpgnat39dhqn6nrjd1imor00
      Item: 2g0001g01b3dtqmst000000220009km800odlkmspb3e9gmct1qdpgnat39dhqn6nrjd1imor00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  heart_of_the_sea:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01krb9dpim6sj1cpq3kq35c5p78nrfcpfn8q35btpmao80
      Item: 500003002m6rrldpq00000044000j9cg01krb9dpim6sj1cpq3kq35c5p78nrfcpfn8q35btpmao80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  fire_charge:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kpj9e9iluor8c5p6ep80
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kpj9e9iluor8c5p6ep80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  name_tag:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79n62rb5btq62po0
      Item: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79n62rb5btq62po0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  apple:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ej1e1o6op80
      Item: k0000c00aorfeln78000000gg002d5i003rdd5n6aoric5j78ej1e1o6op80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  lead:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qdhim2p00
      Item: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qdhim2p00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  cooked_cod:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej3dtnmmpb4bthmup00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej3dtnmmpb4bthmup00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
  spider_eye:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejje1km8pbibtinip80
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejje1km8pbibtinip80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Rotation:
      Chance: 50.0
