Name: <lorange><b>鱼市</b></lorange>
Description:
- <gray>您可以在钓鱼时获得的一切。</gray>
Permission_Required: false
Layout:
  Name: default
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: true
Pages: 1
Icon:
  Material: TROPICAL_FISH