List:
  cod_spawn_egg:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79hmup2vedo62trebtimepo0
      Item: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79hmup2vedo62trebtimepo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 100.0
      BUY: 200.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 0
      Page: 1
  salmon_spawn_egg:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01krb9dpim6sj1cpq3ksr1dhmmurivedo62trebtimepo0
      Item: 500003002m6rrldpq00000044000j9cg01krb9dpim6sj1cpq3ksr1dhmmurivedo62trebtimepo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 100.0
      BUY: 200.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 1
      Page: 1
  tropical_fish_spawn_egg:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip0045mmirj5cdp62pjk79q74rrgd5hm2r2vcpkn6q2vedo62trebtimepo0
      Item: a00006005cdnnarjk000000880016ip0045mmirj5cdp62pjk79q74rrgd5hm2r2vcpkn6q2vedo62trebtimepo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 100.0
      BUY: 200.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 2
      Page: 1
  pufferfish_spawn_egg:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i007jdd5n6aoric5j78ejgelj6cpbicpkn6q2vedo62trebtimepo0
      Item: k0000c00aorfeln78000000gg002d5i007jdd5n6aoric5j78ejgelj6cpbicpkn6q2vedo62trebtimepo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 100.0
      BUY: 200.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 3
      Page: 1
  tripwire_hook:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79q74qbgetkn4pavd1nmuqo0
      Item: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79q74qbgetkn4pavd1nmuqo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 500.0
      BUY: 1000.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 6
      Page: 1
  lily_pad:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79m6ir3pbto62p00
      Item: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79m6ir3pbto62p00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 7
      Page: 1
  leather_boots:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79m6aobkd1in4nr2dtnn8so0
      Item: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79m6aobkd1in4nr2dtnn8so0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 8
      Page: 1
  cooked_cod:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej3dtnmmpb4bthmup00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej3dtnmmpb4bthmup00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 75.0
      BUY: 75.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 9
      Page: 1
  cooked_salmon:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79hmurrbcli5usr1dhmmurg0
      Item: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79hmurrbcli5usr1dhmmurg0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 75.0
      BUY: 75.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 10
      Page: 1
  tropical_fish:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79q74rrgd5hm2r2vcpkn6q00
      Item: a00006005cdnnarjk000000880016ip002tmmirj5cdp62pjk79q74rrgd5hm2r2vcpkn6q00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 300.0
      BUY: 300.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 11
      Page: 1
  pufferfish:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejgelj6cpbicpkn6q00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejgelj6cpbicpkn6q00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 50.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 12
      Page: 1
  ink_sac:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb4008mqqbeclhn4ob6egt6irjbbtpm2oo0
      Item: 180000o00lhmutbeeg00000110004qb4008mqqbeclhn4ob6egt6irjbbtpm2oo0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 16
      Page: 1
  bone:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qc9nmsp80
      Item: 2g0001g01b3dtqmst000000220009km800edlkmspb3e9gmct1qc9nmsp80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 17
      Page: 1
  cod:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79hmup00
      Item: a00006005cdnnarjk000000880016ip001lmmirj5cdp62pjk79hmup00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 50.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 18
      Page: 1
  salmon:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3ksr1dhmmurg0
      Item: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3ksr1dhmmurg0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 50.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 19
      Page: 1
  nautilus_shell:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800odlkmspb3e9gmct1qdpgnat39dhqn6nrjd1imor00
      Item: 2g0001g01b3dtqmst000000220009km800odlkmspb3e9gmct1qdpgnat39dhqn6nrjd1imor00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 5000.0
      BUY: 10000.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 25
      Page: 1
  saddle:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3ksr1chi6op80
      Item: 500003002m6rrldpq00000044000j9cg010rb9dpim6sj1cpq3ksr1chi6op80
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 500.0
      BUY: 1000.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 26
      Page: 1
  bone_meal:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9nmspavdlim2r00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9nmspavdlim2r00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 27
      Page: 1
  bone_meal_1:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9nmspavdlim2r00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9nmspavdlim2r00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 28
      Page: 1
