Name: <yellow><b>方块市场</b></yellow>
Description:
- <gray>建筑方块和资源。</gray>
Permission_Required: false
Layout:
  Name: default
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: true
Pages: 3
Icon:
  Material: JUNGLE_LOG