List:
  white_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejnd1kn8pavetnmur00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ejnd1kn8pavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 10
      Page: 1
  orange_wool:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3krric5n6epavetnmur00
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3krric5n6epavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 11
      Page: 1
  magenta_wool:
    Handler: bukkit_item
    Content:
      Preview: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6qob7cln78oavetnmur00
      Item: 180000o00lhmutbeeg00000110004qb400b6qqbeclhn4ob6egt6qob7cln78oavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 12
      Page: 1
  light_blue_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i006bdd5n6aoric5j78ejcd5jmgt2vc9m7apavetnmur00
      Item: k0000c00aorfeln78000000gg002d5i006bdd5n6aoric5j78ejcd5jmgt2vc9m7apavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 13
      Page: 1
  yellow_wool:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kub5dhm6utqvetnmur00
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3kub5dhm6utqvetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 14
      Page: 1
  lime_wool:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qdhkmqpavetnmur00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qdhkmqpavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 15
      Page: 1
  pink_wool:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qe1kmsqqvetnmur00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qe1kmsqqvetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 16
      Page: 1
  gray_wool:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qctp62uavetnmur00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qctp62uavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 19
      Page: 1
  light_gray_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i006bdd5n6aoric5j78ejcd5jmgt2vctp62uavetnmur00
      Item: k0000c00aorfeln78000000gg002d5i006bdd5n6aoric5j78ejcd5jmgt2vctp62uavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 20
      Page: 1
  cyan_wool:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qcdsm2rivetnmur00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qcdsm2rivetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 21
      Page: 1
  purple_wool:
    Handler: bukkit_item
    Content:
      Preview: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3ks3le9o6opavetnmur00
      Item: 500003002m6rrldpq00000044000j9cg01arb9dpim6sj1cpq3ks3le9o6opavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 22
      Page: 1
  blue_wool:
    Handler: bukkit_item
    Content:
      Preview: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9m7apavetnmur00
      Item: 2g0001g01b3dtqmst000000220009km800jdlkmspb3e9gmct1qc9m7apavetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 23
      Page: 1
  brown_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej2e9nnerivetnmur00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej2e9nnerivetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 24
      Page: 1
  green_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej7e9imarivetnmur00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej7e9imarivetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 25
      Page: 1
  red_wool:
    Handler: bukkit_item
    Content:
      Preview: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79p6ap2vetnmur00
      Item: a00006005cdnnarjk000000880016ip0029mmirj5cdp62pjk79p6ap2vetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 30
      Page: 1
  black_wool:
    Handler: bukkit_item
    Content:
      Preview: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej2dhgm6qqvetnmur00
      Item: k0000c00aorfeln78000000gg002d5i0053dd5n6aoric5j78ej2dhgm6qqvetnmur00
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Required_Permissions: []
    Currency: vault
    Price:
      Type: FLAT
      SELL: 20.0
      BUY: 50.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Discount:
      Allowed: false
    Shop_View:
      Slot: 32
      Page: 1
