Settings:
  # GUI标题。
  Title: <black><b>购物车</b></black>
  # GUI大小。必须是9的倍数。
  # 仅对'CHEST'库存类型有用。
  Size: 54
  # GUI类型。
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
  Inventory_Type: CHEST
  # 设置GUI自动刷新间隔（秒）。设置为0以禁用。
  Auto_Refresh: 0
Product:
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
  # 设置使用'ADD', 'SET' 或 'TAKE'按钮时播放的声音。
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  Sound:
    # 声音名称。您可以使用Spigot的声音名称，或来自您的资源包的名称。
    # Spigot声音: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    Name: ENTITY_ITEM_PICKUP
    # 声音音量。从0.0到1.0。
    Volume: 0.8
    # 声音音高。从0.5到2.0
    Pitch: 1.0
# ==================== GUI CONTENT ====================
# 您可以自由编辑此部分中的项目（添加、移除、修改项目）。
# 以下值可用作按钮类型：
# ADD
# CLOSE
# CONFIRM
# DECLINE
# SET
# SET_CUSTOM
# TAKE
# ==================== ITEM OPTIONS ====================
# > Item: 要显示的项目。请检查：https://github.com/nulli0n/nightcore-spigot/wiki/ItemStack-Options
# > Priority: 按钮优先级。较好的值将覆盖同一插槽中的其他项目。
# > Slots: 按钮插槽。从 [0] 到 [Size - 1]。用逗号分隔。
# > Click_Commands: 点击时执行自定义命令。此处可用PlaceholderAPI。
#     Available click types: LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, NUMBER_1, NUMBER_2, NUMBER_3, NUMBER_4, NUMBER_5, NUMBER_6, NUMBER_7, NUMBER_8, NUMBER_9
#     Use prefix 'player:' to run command by a player.
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: menu open shops
# ==================================================
Content:
  accept:
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: a79a5c95ee17abfef45c8dc224189964944d560f19a44f19f8a46aef3fee4756
      Name: <lgreen><b>接受</b></lgreen>
      Lore:
      - <lgreen><b>详细信息：</b></lgreen>
      - '<lgreen>▪ <lgray>数量: </lgray>%units%</lgreen>'
      - '<lgreen>▪ <lgray>总金额: </lgray>%amount%</lgreen>'
      - '<lgreen>▪ <lgray>价格: </lgray>%price%</lgreen>'
      - '<lgreen>▪ <lgray>余额: </lgray>%balance%</lgreen>'
    Slots: '53'
    Type: confirm
  cancel:
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 27548362a24c0fa8453e4d93e68c5969ddbde57bf6666c0319c1ed1e84d89065
      Name: <lred><b>取消</b></lred>
    Slots: '45'
    Type: decline
  black_stained_glass_pane:
    Priority: 1
    Item:
      Material: BLACK_STAINED_GLASS_PANE
    Slots: 46,47,48,49,50,51,52
    Type: default
  '1':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 6d65ce83f1aa5b6e84f9b233595140d5b6beceb62b6d0c67d1a1d83625ffd
      Name: <lgreen><b>+1</b></lgreen>
    Slots: '42'
    Type: add
    Units: 1
  '8':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: f2ee1371d8f0f5a8b759c291863d704adc421ad519f17462b87704dbf1c78a4
      Name: <lgreen><b>+8</b></lgreen>
    Slots: '43'
    Type: add
    Units: 8
  '16':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 19f62a469a206add73887c7366376a6c4f3377b2f5b979351e96ac634572
      Name: <lgreen><b>+16</b></lgreen>
    Slots: '44'
    Type: add
    Units: 16
  '1_1':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 8d2454e4c67b323d5be953b5b3d54174aa271460374ee28410c5aeae2c11f5
      Name: <lred><b>-1</b></lred>
    Slots: '36'
    Type: take
    Units: 1
  '8_1':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 1683440c6447c195aaf764e27a1259219e91c6d8ab6bd89a11ca8d2cc799fa8
      Name: <lred><b>-8</b></lred>
    Slots: '37'
    Type: take
    Units: 8
  '16_1':
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: ae3e4bc71e3ac330836181eda96bc6f128e5c5313ab952c8ff6ded549e13a5
      Name: <lred><b>-16</b></lred>
    Slots: '38'
    Type: take
    Units: 16
  set_1:
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: bd21b0bafb89721cac494ff2ef52a54a18339858e4dca99a413c42d9f88e0f6
      Name: <lblue><b>设置为1</b></lblue>
    Slots: '39'
    Type: set
    Units: 1
  set_max:
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: d5e1be33374fd7b2bae9c8fc9146b6ed3eedcb1476b3b7b8010f5f44bfa843e
      Name: <lblue><b>设置为最大</b></lblue>
    Slots: '40'
    Type: set
    Units: 10000
  set_custom:
    Priority: 100
    Item:
      Material: PLAYER_HEAD
      SkinURL: 117f3666d3cedfae57778c78230d480c719fd5f65ffa2ad3255385e433b86e
      Name: <lblue><b>自定义设置</b></lblue>
    Slots: '41'
    Type: set_custom
    Units: 1