Name: <lred><b>材料</b></lred>
Description:
- <gray>药水和材料。</gray>
Permission_Required: false
Layout:
  Name: default
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: true
Pages: 1
Icon:
  Material: REDSTONE